name: CI #test
on:
  push:
  pull_request:

jobs:
  running_tests:
    strategy:
      matrix: 
        os: [ ubuntu-latest ]
        python-version:
          - "3.9"
    name: TESTS
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: mongo-svc
      uses: art049/mongodb-cluster-action@v0

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run the application
      run: |
        cd app
        export FLASK_APP=main.py
        echo "hello world!"
        flask run &
      

    - name: Run Python tests
      run: pytest
  docker_build_and_push:
    needs: running_tests  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        tags: lironderi/market-app:latest

    - name: Trigger ArgoCD Sync
      run: |
        git clone https://github.com/danielsagie/project_conf
        git config --global user.email "danielsagie688@gmail.com"
        git config --global user.name "Daniel"
        pwd
        cd project_conf
        echo "Trigger change" >> trigger.txt
        sed -i "s|image: lironderi/market-app:v1.0.*|image: lironderi/market-app:v1.0.${{ github.run_id }}|" k8s_conf/deployment.yaml
        git add trigger.txt
        git commit -m "Trigger ArgoCD Sync"
        git push https://${{ secrets.GH_PAT }}@github.com/danielsagie/project_conf.git
